{% set python_min = "3.10" %}
{% set name = "nexus2srs" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nexus2srs-{{ version }}.tar.gz
  sha256: f0562b6f9e25c98b5587771860f0114cb19bcab767d7569112dfd35640da6d8c

build:
  entry_points:
    - nexus2srs = nexus2srs.cli:cli_nexus2srs
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - pytest
    - numpy
    - h5py
    - hdf5plugin
    - hdfmap
    - pillow
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - h5py
    - hdf5plugin
    - hdfmap
    - pillow

test:
  imports:
    - nexus2srs
  commands:
    - pip check
    - nexus2srs --help
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Program to convert NeXus (.nxs) scan Files to the classic ASCII SRS .dat files.
  home: https://github.com/DiamondLightSource/nexus2srs
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DanPorter
    - PeterC-DLS
